"""Build and verify an unsigned, reproducible local release candidate.

The gate intentionally owns its temporary virtual environment and PyInstaller
work directories.  It leaves only machine-readable release evidence under the
requested output directory and never invokes a signing tool.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import platform
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


GATE_SCHEMA_VERSION = 1
DEFAULT_TIMEOUT_SECONDS = 1800
_VERSION_RE = re.compile(r'^APP_VERSION\s*=\s*["\']([^"\']+)["\']', re.MULTILINE)
_GENERATED_OUTPUTS = {
    "ImgConverter.exe", "ImgConverter", "ImgConverter.exe.sha256",
    "ImgConverter.sha256", "dependencies.txt", "sbom.json",
    "provenance.json", "release-manifest.json", "SHA256SUMS",
}


class GateError(RuntimeError):
    """A release-gate step failed or produced an incomplete artifact."""


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _read_app_version(repo_root: Path) -> str:
    source = (repo_root / "imgconverter.py").read_text(encoding="utf-8")
    match = _VERSION_RE.search(source)
    if not match:
        raise GateError("could not read APP_VERSION from imgconverter.py")
    return match.group(1)


def _run(
    command: list[str],
    *,
    cwd: Path,
    env: dict[str, str],
    log_path: Path,
    timeout: int,
) -> subprocess.CompletedProcess[str]:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        completed = subprocess.run(
            command,
            cwd=str(cwd),
            env=env,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=timeout,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
        )
    except subprocess.TimeoutExpired as exc:
        stdout = exc.stdout or ""
        stderr = exc.stderr or ""
        log_path.write_text(
            f"TIMEOUT after {timeout}s\n\n{stdout}\n{stderr}",
            encoding="utf-8",
        )
        raise GateError(
            f"command timed out after {timeout}s; see {log_path}"
        ) from exc
    log_path.write_text(
        "$ " + " ".join(command) + "\n\n" + completed.stdout + completed.stderr,
        encoding="utf-8",
    )
    if completed.returncode != 0:
        raise GateError(
            f"command exited {completed.returncode}; see {log_path}"
        )
    return completed


def _write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(
        json.dumps(payload, indent=2, sort_keys=True, default=str) + "\n",
        encoding="utf-8",
    )
    os.replace(temporary, path)


def _reset_output_dir(output_dir: Path) -> None:
    """Remove only files generated by this gate from its dedicated output dir."""
    for name in _GENERATED_OUTPUTS:
        path = output_dir / name
        if path.is_file() or path.is_symlink():
            path.unlink()
    logs = output_dir / "logs"
    if logs.is_dir():
        shutil.rmtree(logs)


def _redact_temporary(value: object, temporary_root: Path) -> object:
    if isinstance(value, str):
        return value.replace(str(temporary_root), "<temporary>")
    if isinstance(value, list):
        return [_redact_temporary(item, temporary_root) for item in value]
    if isinstance(value, dict):
        return {
            key: _redact_temporary(item, temporary_root)
            for key, item in value.items()
        }
    return value


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _git_value(repo_root: Path, *args: str) -> str | None:
    try:
        completed = subprocess.run(
            ["git", *args],
            cwd=str(repo_root),
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=30,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if completed.returncode:
        return None
    return completed.stdout.strip() or None


def _venv_python(venv_dir: Path) -> Path:
    if os.name == "nt":
        return venv_dir / "Scripts" / "python.exe"
    return venv_dir / "bin" / "python"


def _pip_list(
    python: Path, *, repo_root: Path, env: dict[str, str], logs: Path, timeout: int,
) -> list[dict[str, str]]:
    completed = _run(
        [str(python), "-m", "pip", "list", "--format=json"],
        cwd=repo_root,
        env=env,
        log_path=logs / "pip-list.log",
        timeout=timeout,
    )
    try:
        payload = json.loads(completed.stdout)
    except json.JSONDecodeError as exc:
        raise GateError("pip list did not return JSON") from exc
    if not isinstance(payload, list):
        raise GateError("pip list returned a non-list payload")
    return [
        {"name": str(item["name"]), "version": str(item["version"])}
        for item in payload
        if isinstance(item, dict) and "name" in item and "version" in item
    ]


def _build_sbom(packages: list[dict[str, str]]) -> dict:
    components = []
    for package in sorted(packages, key=lambda item: item["name"].casefold()):
        normalized = re.sub(r"[-_.]+", "-", package["name"]).lower()
        components.append({
            "name": package["name"],
            "version": package["version"],
            "purl": f"pkg:pypi/{normalized}/{package['version']}",
        })
    return {
        "schema_version": GATE_SCHEMA_VERSION,
        "bom_format": "imgconverter-local-sbom",
        "components": components,
    }


def _smoke_environment(smoke_home: Path) -> dict[str, str]:
    environment = os.environ.copy()
    # Keep packaged CLI history, journal, presets, and Qt state out of the
    # operator's profile while retaining an entirely headless execution path.
    environment["HOME"] = str(smoke_home)
    environment["USERPROFILE"] = str(smoke_home)
    environment["PIP_CACHE_DIR"] = str(smoke_home / "pip-cache")
    environment["QT_QPA_PLATFORM"] = "offscreen"
    environment["PYTHONUTF8"] = "1"
    return environment


def _run_gate(args: argparse.Namespace) -> Path:
    repo_root = Path(args.repo_root).expanduser().resolve()
    output_dir = Path(args.output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    _reset_output_dir(output_dir)
    logs = output_dir / "logs"
    logs.mkdir(parents=True, exist_ok=True)
    version = _read_app_version(repo_root)
    gate_timeout = max(60, int(args.timeout))

    with tempfile.TemporaryDirectory(prefix="imgconverter-release-gate-") as temp_name:
        temporary_root = Path(temp_name)
        venv_dir = temporary_root / "venv"
        smoke_home = temporary_root / "home"
        smoke_home.mkdir()
        smoke_workspace = temporary_root / "smoke"
        fixture_input = smoke_workspace / "input"
        fixture_output = smoke_workspace / "output"
        fixture_input.mkdir(parents=True)
        fixture_output.mkdir(parents=True)
        env = _smoke_environment(smoke_home)

        _run(
            [sys.executable, "-m", "venv", str(venv_dir)],
            cwd=repo_root,
            env=env,
            log_path=logs / "venv.log",
            timeout=gate_timeout,
        )
        python = _venv_python(venv_dir)
        if not python.is_file():
            raise GateError(f"virtualenv Python was not created at {python}")

        _run(
            [str(python), "-m", "pip", "install", "--upgrade", "pip"],
            cwd=repo_root,
            env=env,
            log_path=logs / "pip-upgrade.log",
            timeout=gate_timeout,
        )
        _run(
            [str(python), "-m", "pip", "install", "--disable-pip-version-check",
             "-r", str(repo_root / "requirements.txt")],
            cwd=repo_root,
            env=env,
            log_path=logs / "pip-runtime.log",
            timeout=gate_timeout,
        )
        _run(
            [str(python), "-m", "pip", "install", "--disable-pip-version-check",
             ".[all,dev]"],
            cwd=repo_root,
            env=env,
            log_path=logs / "pip-all-dev.log",
            timeout=gate_timeout,
        )
        _run(
            [str(python), "-m", "pip", "check"],
            cwd=repo_root,
            env=env,
            log_path=logs / "pip-check.log",
            timeout=gate_timeout,
        )
        packages = _pip_list(
            python, repo_root=repo_root, env=env, logs=logs, timeout=gate_timeout,
        )
        dependencies = _run(
            [str(python), "-m", "pip", "freeze", "--all"],
            cwd=repo_root,
            env=env,
            log_path=logs / "pip-freeze.log",
            timeout=gate_timeout,
        )
        (output_dir / "dependencies.txt").write_text(
            dependencies.stdout, encoding="utf-8",
        )
        _write_json(output_dir / "sbom.json", _build_sbom(packages))

        _run(
            [str(python), "-m", "pytest", "-q", "--basetemp",
             str(temporary_root / "pytest-tmp")],
            cwd=repo_root,
            env=env,
            log_path=logs / "pytest.log",
            timeout=gate_timeout,
        )

        stage_dist = temporary_root / "dist"
        stage_build = temporary_root / "build"
        _run(
            [str(python), "-m", "PyInstaller", "--noconfirm", "--clean",
             "--distpath", str(stage_dist), "--workpath", str(stage_build),
             str(repo_root / "ImgConverter.spec")],
            cwd=repo_root,
            env=env,
            log_path=logs / "pyinstaller.log",
            timeout=gate_timeout,
        )
        built_artifact = stage_dist / ("ImgConverter.exe" if os.name == "nt" else "ImgConverter")
        if not built_artifact.is_file() or built_artifact.stat().st_size == 0:
            raise GateError(f"PyInstaller did not produce {built_artifact}")
        artifact = output_dir / built_artifact.name
        shutil.copy2(built_artifact, artifact)

        fixture_script = (
            "from PIL import Image; import sys; "
            "Image.new('RGB', (48, 32), (22, 48, 78)).save(sys.argv[1])"
        )
        _run(
            [str(python), "-c", fixture_script, str(fixture_input / "sample.bmp")],
            cwd=repo_root,
            env=env,
            log_path=logs / "fixture.log",
            timeout=gate_timeout,
        )

        smoke_results: dict[str, dict[str, object]] = {}
        smoke_commands = {
            "version": ["--version"],
            "format_matrix": ["--format-matrix"],
            "backend_info": ["--backend-info"],
            "conversion": [
                "--input", str(fixture_input), "--output", str(fixture_output),
                "--format", "png", "--no-recursive", "--workers", "1",
            ],
        }
        for name, command_args in smoke_commands.items():
            completed = _run(
                [str(artifact), *command_args],
                cwd=repo_root,
                env=env,
                log_path=logs / f"smoke-{name}.log",
                timeout=300,
            )
            smoke_results[name] = {
                "args": _redact_temporary(command_args, temporary_root),
                "returncode": completed.returncode,
                "stdout": _redact_temporary(completed.stdout, temporary_root),
                "stderr": _redact_temporary(completed.stderr, temporary_root),
            }

        converted = fixture_output / "sample.png"
        if not converted.is_file() or converted.stat().st_size == 0:
            raise GateError("packaged CLI smoke conversion did not produce sample.png")
        _run(
            [str(python), "-c",
             "from PIL import Image; import sys; "
             "Image.open(sys.argv[1]).verify()", str(converted)],
            cwd=repo_root,
            env=env,
            log_path=logs / "smoke-conversion-verify.log",
            timeout=300,
        )

        artifact_hash = _sha256(artifact)
        sha_path = output_dir / f"{artifact.name}.sha256"
        sha_path.write_text(f"{artifact_hash}  {artifact.name}\n", encoding="utf-8")
        provenance = {
            "schema_version": GATE_SCHEMA_VERSION,
            "app": "ImgConverter",
            "version": version,
            "repository": _git_value(repo_root, "config", "--get", "remote.origin.url"),
            "commit": _git_value(repo_root, "rev-parse", "HEAD"),
            "working_tree_dirty": bool(_git_value(repo_root, "status", "--porcelain")),
            "platform": {
                "system": platform.system(),
                "release": platform.release(),
                "machine": platform.machine(),
                "python": sys.version,
            },
            "build": {
                "command": "python -m PyInstaller --noconfirm --clean ImgConverter.spec",
                "unsigned": True,
                "codesign": False,
            },
            "artifact": {
                "name": artifact.name,
                "bytes": artifact.stat().st_size,
                "sha256": artifact_hash,
            },
            "smoke": smoke_results,
        }
        _write_json(output_dir / "provenance.json", provenance)
        evidence = {
            name: {
                "bytes": path.stat().st_size,
                "sha256": _sha256(path),
            }
            for name in (
                artifact.name, f"{artifact.name}.sha256", "dependencies.txt",
                "sbom.json", "provenance.json",
            )
            for path in [output_dir / name]
        }
        manifest = {
            "schema_version": GATE_SCHEMA_VERSION,
            "app": "ImgConverter",
            "version": version,
            "artifact": evidence[artifact.name],
            "evidence": evidence,
            "smoke": smoke_results,
            "unsigned": True,
        }
        _write_json(output_dir / "release-manifest.json", manifest)
        checksum_files = [
            artifact, sha_path, output_dir / "dependencies.txt",
            output_dir / "sbom.json", output_dir / "provenance.json",
            output_dir / "release-manifest.json",
        ]
        (output_dir / "SHA256SUMS").write_text(
            "".join(f"{_sha256(path)}  {path.name}\n" for path in checksum_files),
            encoding="utf-8",
        )

    return output_dir


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=_repo_root())
    parser.add_argument(
        "--output-dir", type=Path,
        default=_repo_root() / "dist" / "release-gate",
    )
    parser.add_argument(
        "--timeout", type=int, default=DEFAULT_TIMEOUT_SECONDS,
        help="timeout in seconds for each isolated install/test/build step",
    )
    args = parser.parse_args(argv)
    try:
        output = _run_gate(args)
    except (GateError, OSError, ValueError) as exc:
        print(f"[release-gate] FAILED: {exc}", file=sys.stderr)
        return 1
    print(f"[release-gate] PASS: {output / 'release-manifest.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
